defmodule Lua.Compiler.Erlang.Runtime do
  @moduledoc false
  # Runtime helpers called by code generated by `Lua.Compiler.Erlang`.
  #
  # The codegen emits remote calls into this module rather than inlining
  # small loops as Erlang abstract forms — much easier to maintain when
  # the helper is non-trivial.
  #
  # Functions here must stay backward-compatible with previously-loaded
  # compiled modules (no signature changes) — those modules can outlive
  # the current build's `Lua` deps until B5b's build-hash purging is in
  # place.

  @doc """
  Copies up to `count` args into the first `count` slots of `regs`.

  Mirrors the interpreter's argument-binding behaviour (see
  `Lua.VM.Executor.copy_args_to_regs/5`). Missing args land as `nil`.
  Extra args are ignored (they go into `proto.varargs` for vararg
  functions; the codegen handles that case in B5d).
  """
  @spec copy_args([term()], tuple(), non_neg_integer(), non_neg_integer()) :: tuple()
  def copy_args(_args, regs, _i, 0), do: regs

  def copy_args([], regs, i, count) when count > 0 do
    # Out of args; remaining param slots are nil. `make_tuple/2` already
    # initialised the tuple with nil, so just stop.
    _ = i
    regs
  end

  def copy_args([arg | rest], regs, i, count) do
    copy_args(rest, :erlang.setelement(i + 1, regs, arg), i + 1, count - 1)
  end
end
