name: Publish to Hex.pm

on:
  release:
    types: [published]

jobs:
  Publish:
    runs-on: ubuntu-latest
    env:
      HEX_API_KEY: ${{ secrets.HEXPM_SECRET }}
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.16.1'
          otp-version: '26.2.1'
      - run: mix deps.get
      - run: mix compile --docs
      - run: mix hex.publish --yes
